TZ = ZoneInfo("Asia/Tokyo")
CONDITION_LIMIT = 20
APP_ROUTE = getenv("APP_ROUTE", "../")
FRONTEND_CONTENTS_PATH = APP_ROUTE + "public"
JIA_JWT_SIGNING_KEY_PATH = APP_ROUTE + "ec256-public.pem"
DEFAULT_ICON_FILE_PATH = APP_ROUTE + "NoImage.jpg"
DEFAULT_JIA_SERVICE_URL = "http://localhost:5000"
MYSQL_ERR_NUM_DUPLICATE_ENTRY = 1062

